# Generated by Django 3.0.5 on 2020-10-27 13:38

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='serialized_data',
            field=encrypted_fields.fields.EncryptedTextField(help_text='The serialized form of this version of the model.'),
        ),
    ]
