# Generated by Django 3.0.5 on 2020-10-27 14:46

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0002_auto_20201027_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='object_repr',
            field=encrypted_fields.fields.EncryptedTextField(help_text='A string representation of the object.'),
        ),
    ]
